apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5001
  selector:
    app: orderservice
