apiVersion: v1
kind: Service
metadata:
  name: productservice
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: prodcutservice
