image:
  repository: moyg12/orderservice
  tag: 'b0611a4e16ada28f5d3de6200679a4eae9cdaf95'
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80         
  targetPort: 8080 

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75