image:
  repository: moyg12/orderservice
  tag: '2579475fa5575d99520179b7c4553bfc821cf3e6'
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80         
  targetPort: 8080 

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75