image:
  repository: moyg12/orderservice
  tag: '581eba9d852bdad27137302b3a0af217a725867d'
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80         
  targetPort: 8080 

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75