image:
  repository: moyg12/productservice
  tag: latest                          
  pullPolicy: IfNotPresent

service:
  targetPort: 80
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75