apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: orderservice
